### ISSUE TITLE
Turning becomes very sluggish while moving

### ISSUE THREAD

**Issue by Barugon** [TwistedTwigleg/Godot_FPS_Tutorial#11] opened 2018-03-20 17:51 UTC
If I'm standing still and turning around using the mouse then it's very smooth. If I start moving by holding any of the direction keys then turning with the mouse becomes very sluggish. If I'm using a touchpad then I cannot turn at all while moving.

I'm using Fedora 27 64 bit.

**Comment by TwistedTwigleg** [comment] 2018-03-20 22:11
Thanks Barugon!

I’m not sure it will make much of a difference, but which version of Godot are you using? It may be something has changed from the version I am using (Godot 3.0.2)

I’ll test on my Linux machine and see if I can replicate it. I’m using Ubuntu 16.4 LTS, so I should in theory have a good chance of replicating it (Assuming it is not the OS that is the problem. I highly doubt the OS is the problem though)

**Comment by Barugon** [comment] 2018-03-29 20:27
The version I'm using is 3.0.2.

**Comment by TwistedTwigleg** [comment] 2018-03-29 21:15
Okay. I haven't had a chance to look at this yet, but I will soon (before part 5 is out)
Thanks!

**Comment by TwistedTwigleg** [comment] 2018-04-04 14:22
Well, I can confirm the bug is still active in master branch (with part 5 code). After some testing, I think the problem is because of setting the mouse mode to `MOUSE_MODE_CAPTURED`, since it seems to be smooth when I change it to `MOUSE_MODE_CONFINED`.

This issue may also be present in Windows, I'll update this comment once I've checked.
Edit: It seems to be a Linux only bug, as I cannot reproduce it in Windows.

It's likely the bug is related to issue [17288](https://github.com/godotengine/godot/issues/17288) in the Godot repository. Might also be related to issue 14855 as well.

I'm not sure how to fix this just yet. Maybe I need to move mouse delta calculations into `_physics_process`?

**Comment by EzraT** [comment] 2018-06-21 11:42
> I'm not sure how to fix this just yet. Maybe I need to move mouse delta calculations into _physics_process?

@TwistedTwigleg I have tried this in every way I could think of, using either _physics_process or _process, and the same issue still occurs for me, (in 3.0.3 as well), it doesn't seem to make a difference.
Turning off MOUSE_MODE_CAPTURED makes it smooth for me as well.

**Comment by TwistedTwigleg** [comment] 2018-06-21 15:56
> @TwistedTwigleg I have tried this in every way I could think of, using either _physics_process or _process, and the same issue still occurs for me, (in 3.0.3 as well), it doesn't seem to make a difference.
> Turning off MOUSE_MODE_CAPTURED makes it smooth for me as well.

Strange. I'm really not sure what is causing the issue. I also could not find any way to get smooth mouse movement using `_physics_process` or `_process`. I did have a sort of working method, but unfortunately it did not work if the mouse was moved too fast, and I forgot to save the code.

My hunch is that this bug is a engine related, since using `MOUSE_MODE_CAPTURED` should not cause any (or at least not any major) performance hits, and while the code is not heavily optimized, it should be fast enough for most computers, and turning off `MOUSE_MODE_CAPTURED` should not really change anything.

________

I'm not really sure what to do here though. I would suggest opening a Github issue on the Godot engine repository, linking to the FPS project (if you need a example project). I really think the bug is engine related, since I do not see what else could be causing the problem (though maybe I missed something?).

**Comment by EzraT** [comment] 2018-06-21 23:56
I think it is engine related too, there are already a couple issues on the Godot repo describing it, but no answers yet.
https://github.com/godotengine/godot/issues/17288
https://github.com/godotengine/godot/issues/14855

**Comment by TwistedTwigleg** [comment] 2018-06-22 01:01
I suppose we'll have to wait until someone fixes it then, and/or a solution is found. Hopefully we won't have to wait too long.

**Comment by Barugon** [comment] 2018-07-03 21:53
I was going to try this in Godot 3.0.4 but I get the following error when I load the project:
```
ERROR: _load_settings_text_or_binary: Couldn't load file '/home/ivan/Downloads/Godot_FPS_Tutorial-master/project.godot', error code 12.
```

**Comment by TwistedTwigleg** [comment] 2018-07-04 01:12
> I was going to try this in Godot 3.0.4 but I get the following error when I load the project:

Hey Barugon! Sorry about the late reply!

The reason the project is not opening with Godot version 3.0.4 is because some changes were added to make it work with Godot master (Godot 3.1). You can still open it in Godot 3.0.4, you just need to open the `project.godot` file in a text editor, and the line that says `config_version=4` to `config_version=3` and then it will open with Godot 3.0.4.

The other thing you will need to do is change `vel = move_and_slide(vel,Vector3(0,1,0), true, 0.05, 4, deg2rad(MAX_SLOPE_ANGLE))` to `vel = move_and_slide(vel,Vector3(0,1,0), 0.05, 4, deg2rad(MAX_SLOPE_ANGLE))` in `Player.gd`. (You will need to do this if you open the project in Godot 3.0.4 or Godot 3.1 / Godot master)

The reason for the change is because in a old version of Godot 3.1 `move_and_slide` took a additional (required) argument. Now the additional argument is optional, but they moved it so it is the last argument, which means we have to use (`vel = move_and_slide(vel,Vector3(0,1,0), 0.05, 4, deg2rad(MAX_SLOPE_ANGLE))`) again to get the project to work.

I'll try to get a PR fixing this, updating the documentation, and updating all of the zip flies in the documentation when I am back from vacation.

If you use Godot 3.0, You may need to add all of the input map actions back, because for some reason it seems they all disappear... Not sure why this happens.

Sorry for the inconvenience!

Personally, I would suggest downloading a nightly build of Godot 3.1. I did not realize opening the project in Godot 3.1 would make it incompatible with Godot 3.0, otherwise I would probably have waited for Godot 3.1 to be out before updating.

You can find daily/nightly [builds by Calinou here](https://hugo.pro/projects/godot-builds/) if you want to go the Godot 3.1 route.

Thanks for letting me know about the error, and sorry for the inconvenience!

**Comment by Barugon** [comment] 2018-07-05 02:08
I modified the files and got it to load but keyboard input doesn't work at all in 3.0.4. I compiled the Godot master branch and the framerate was really low (5 FPS or less). I recompiled with target=release_debug and everything seemed OK.

**Comment by TwistedTwigleg** [comment] 2018-07-05 17:07
> I modified the files and got it to load but keyboard input doesn't work at all in 3.0.4.

Did you look at the input mappings? When I loaded it in Godot 3.0.4, the project lost all of the input mappings for some reason.

> I compiled the Godot master branch and the framerate was really low (5 FPS or less). I recompiled with target=release_debug and everything seemed OK.

Strange, I wonder the framerate drops unless it is a debug build. My guess is it has something to do with the `GridMap` node, as I cannot think of what else could be causing such a dramatic frame rate drop (well, outside of the code, which last I looked I did not see anything that would suggest the code is the issue)

Thinking about it, it is probably related to [this issue](https://github.com/godotengine/godot-docs/issues/1412) on the documentation repository. I'm not sure on a fix though, as when I looked I didn't see anything strange in the project settings.

**Comment by EzraT** [comment] 2018-07-21 20:34
I'm starting to think that this is at-least partially OS related, I recently switched Linux distro's (from Ubuntu Budgie 18.04, to Linux Mint 19 specifically) and, to my surprise, this issue doesn't seem to happen anymore in the projects I've tried it with so far, I no longer get the weird stuttering and hitching after the switch, with the same Nvidia Driver version installed as-well.

I don't know for sure if this is actually related to something in Linux Mint being setup differently or something, but I do find it quite odd that the previous distro's I used, namely Xubuntu 17.04, and Ubuntu Budgie 18.04, all very clearly suffer from this problem, there are even people on Windows 10 who have reported on it too.

I am of course happy that it no longer seems to happen on my end, but at the same time I still have no idea what it is exactly causing this issue, this should work the same way across all OS's right?

Tested on both 3.0.5 and the (at the time of writing) latest master.

**Comment by TwistedTwigleg** [comment] 2018-07-22 20:46
> I'm starting to think that this is at-least partially OS related, I recently switched Linux distro's (from Ubuntu Budgie 18.04, to Linux Mint 19 specifically) and, to my surprise, this issue doesn't seem to happen anymore in the projects I've tried it with so far, I no longer get the weird stuttering and hitching after the switch, with the same Nvidia Driver version installed as-well.

Interesting! Maybe it's not a graphics related issue, but is instead something OS related.

> I am of course happy that it no longer seems to happen on my end, but at the same time I still have no idea what it is exactly causing this issue, this should work the same way across all OS's right?

Yeah, it should be the same across all of the OS's. I'm really stumped as to what could be causing this issue. Maybe another driver was causing the issue, like the mouse driver?

I am glad it is working for you now! I am also glad to know it does not seem to be a problem with the project, or at least it's not totally a problem with the project.

**Comment by ghost** [comment] 2018-08-10 09:56
Shouldn't this issue be closed by now?

**Comment by TwistedTwigleg** [comment] 2018-08-10 10:55
> Shouldn’t this issue be closed by now?

Probably. I’ve left it open because the performance issue was never fixed. The mouse issue was more or less determined to be a engine bug, but we never determined what was causing the performance drops.

According to someone on the documentation repository on GitHub (I’m on mobile, so I do not have a link) performance is much better if you remove the WorldEnvrioment node. That may fix the issue? I have not had time to check since I’m working on another tutorial series, but maybe it will fix both the performance issue and the mouse issue?. Once I get the tutorials I’m working on done, I’ll try to improve performance on the FPS.

Anyway, I’ll close this since the bug seems to be mostly engine related as far as the mouse goes.  As for performance p, I’ll see what I can do in the future.

Thanks for the reminder onionbo!
Closing issue...

**Closed as completed by TwistedTwigleg** 2018-08-10 10:55 UTC
Labels: bug
