### ISSUE TITLE
Video Card not supported

### ISSUE THREAD

**Issue by ElectroGamesDev** [TwistedTwigleg/Godot_FPS_Tutorial#29] opened 2019-12-22 03:16 UTC
It says "Your Video Card driver does not support any of the supported OpenGL versions" when i try to play.

**Comment by TwistedTwigleg** [comment] 2019-12-22 04:02
Hi @ElectroGamesYT 

Based on the error, it sounds like your graphics card does not support OpenGL 3.3, which is what the FPS project uses to run. Do other Godot projects run successfully? Do you get any other errors?

If other Godot projects work, then the issue is probably because the FPS tutorial uses OpenGL 3. You might be able to run the project by converting the project to OpenGL 2 using the GLES2 backend. You can click the red text that says “GLES3” in the top right on the Godot editor and select “GLES2” and then it might work (though the visuals make not look as good)

That said, the project not opening due to an issue with graphics card support is more a Godot engine related issue than it is an issue for this project. Because this issue is not directly related to the FPS project, I am closing this issue.

___________

Side Note: Discussion for general Godot engine help may be better suited for one of the communities on the Godot communities portion of the Godot website. That way other members of the Godot community can see your post and potentially offer solutions.

**Closed as completed by TwistedTwigleg** 2019-12-22 04:02 UTC
Labels: question, wontfix
