### ISSUE TITLE
Stuck standing still, can't move.

### ISSUE THREAD

**Issue by dodgyville** [TwistedTwigleg/Godot_FPS_Tutorial#3] opened 2018-02-27 06:19 UTC
Great tutorial but I can't seem to move around. Mouse controls direction but keys/joypad don't appear to have an affect. This is on a clone of the repo.

**Comment by TwistedTwigleg** [comment] 2018-02-27 13:58
Thanks dogyville!

I just download a zip of the repository to a clean directory and its work fine for me on Linux (Ubuntu 16.4 LTS) using Godot 3.0 stable. The controls are WASD and arrow keys to move around by default (with no joypad support currently).

What version of Godot are you using, and on which OS? Can you check the input map settings, making sure the `movement_<insert_direction_here>` actions are setup?

Also, does the KinematicCharacter demo work? The movement code is heavily based after the KinematicCharacter demo, so it would be a good cross reference test.

**Comment by dodgyville** [comment] 2018-02-27 23:05
Hmm, it works using 3.0 stable (I'm also on linux :+1: ) but not on tip. Probably something to do with my setup. Oh well! Thanks so much

I'd love a bit more detail on how player collision with walls is handled but other than that the tutorial is great.

**Comment by TwistedTwigleg** [comment] 2018-02-27 23:53
> Hmm, it works using 3.0 stable (I'm also on linux +1 ) but not on tip. Probably something to do with my setup. Oh well! Thanks so much

No problem! Let me know if anything else comes up.

I should probably compile and run master to see if it's broken anything. It could be something in master has changed how input is handled and/or how collisions are handled. I'll take a look and reopen this issue if I cannot get the project working.

> I'd love a bit more detail on how player collision with walls is handled but other than that the tutorial is great.

Thanks!

I'm not doing anything special for player to wall collisions. 

The collision handling code is exactly the same as Kinematic character demo, I'm just using a capsule with a box on the bottom instead of just a box.

I didn't think to add details about wall collisions since it was so similar to the demo. What details about wall collisions are you looking for? Any bugs I should be looking for? (I'm just curious because I've never had any issues with wall collisions, but it is entirely possible I just do not know where to look)

**Comment by dodgyville** [comment] 2018-02-28 00:21
>  What details about wall collisions are you looking for? Any bugs I should be looking for?

It's unrelated to your fine demo. In my FPS project I'm controlling the camera in _process and I have no idea how to stop it walking through walls

**Comment by TwistedTwigleg** [comment] 2018-02-28 01:14
Well, I just tested the project with master, and the player does not move. I'm not sure if the issue is in Godot, or in the project... Will need to do further testing.

Regardless, I can confirm this is a bug when running from a Godot master build.

____

> It's unrelated to your fine demo. In my FPS project I'm controlling the camera in _process and I have no idea how to stop it walking through walls

Have you tried moving the camera in `_physics_process`? Physics process is called every physics tick, so it may sync better the physics (assuming your camera is attached to a physics body)

Hopefully you will find a solution! (Also, let me know when it is finished! I'd love to see it )

**Comment by TwistedTwigleg** [comment] 2018-03-01 16:32
A new argument was introduced for `move_and_slide`, which was causing the issue.

When Godot 3.1 comes out, the tutorial will need to be updated to change
`vel = move_and_slide(vel,Vector3(0,1,0), 0.05, 4, deg2rad(MAX_SLOPE_ANGLE))`
to
`vel = move_and_slide(vel,Vector3(0,1,0), true, 0.05, 4, deg2rad(MAX_SLOPE_ANGLE))`

**Comment by TwistedTwigleg** [comment] 2018-05-22 14:06
Closed via #19.
Thanks for reporting the bug!

**Closed as completed** 2018-05-22 14:05 UTC
Labels: bug
